# from the page of "Python Projects – Beginner to Advanced"
# at https://www.geeksforgeeks.org/python-projects-beginner-to-advanced/
# this is the first project "Num5ber guessing game in Python"
# at https://www.geeksforgeeks.org/number-guessing-game-in-python/
# Project Description:
#     Build a Number guessing game, in which the user selects a range.
#     Let’s say User selected a range, i.e., from A to B, where A and B belong to Integer.
#     Some random integer will be selected by the system and the user has to guess that integer
#     in the minimum number of guesses
import random

print("welcome to the Number Guessing Game\n")
while 1:
    try:
        strList = input("Enter the range of integer as 2 space-separated integers: \n").split()
        if len(strList) != 2:
            raise ValueError
        a = int(strList[0])
        b = int(strList[1])
        if b <= a:
            raise SyntaxError()
    except ValueError:
        print("You Must enter 2 integers\nTry again ....\n")
    except SyntaxError:
        print("You Must enter 2 different integers with the smaller integer first\nTry again ....\n")
    else:
        print("Your input is ", a, "and ", b)
        break

# a random number will be generated by the program
N = random.randint(a, b)
cnt = 0
while 1:
    try:
        g = int(input("Guess the number:\n"))
        if g<a or g>b:
            raise ValueError
    except ValueError:
        print("You must input a single integer number between ", a, " and ", b)
    else:
        cnt +=1
        if g == N:
            print("C O N G R T U L A T I O N .... you guessed the number in ", cnt," iteration\nGood by.")
            break
        elif g > N:
            print("your guess is larger than it should be. Try again: ")
        else:
            print("your guess is smaller than it should be. Try again: ")
